ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [WP7DatabaseProject], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DEV_BUILD.mdf', SIZE = 2304 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

