-- =============================================
-- Script Template
-- =============================================
SET IDENTITY_INSERT [dbo].[RecipeNutritional] ON
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (1, 'AMERICAN SUB ', '1 each', 'AMERICAN SUB ', '123 g', '70 g', '1', '15', '42', '43', '70', 1)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (2, 'SPICY POTATO KALE ', '2 each', 'SPICY POTATO KALE ', '133 g', '71 g', '2', '16', '41', '44', '69', 2)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (3, 'FRENCH FRIES ', '3 each', 'FRENCH FRIES ', '143 g', '72 g', '3', '17', '40', '45', '68', 3)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (4, 'CRAB CAKE ', '4 each', 'CRAB CAKE ', '153 g', '73 g', '4', '18', '39', '46', '67', 4)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (5, 'ROASTED CORN ', '5 each', 'ROASTED CORN ', '163 g', '74 g', '5', '19', '38', '47', '66', 5)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (6, 'CAJUN CHICKEN CHILI ', '6 each', 'CAJUN CHICKEN CHILI ', '173 g', '75 g', '6', '20', '37', '48', '65', 6)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (7, 'SALAD, COBB, FRESH FRUIT ', '7 each', 'SALAD, COBB, FRESH FRUIT ', '183 g', '60 g', '7', '21', '36', '49', '64', 7)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (8, 'GREMOLADA WRAP  ', '8 each', 'GREMOLADA WRAP  ', '193 g', '61 g', '8', '22', '35', '50', '63', 8)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (9, 'FIESTA PASTA ', '9 each', 'FIESTA PASTA ', '223 g', '62 g', '9', '23', '34', '51', '62', 9)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (10, 'MARINARA SAUCE  ', '10 each', 'MARINARA SAUCE  ', '233 g', '63 g', '10', '24', '33', '52', '61', 10)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (11, 'PEPPERONI PIZZA ', '11 each', 'PEPPERONI PIZZA ', '243 g', '64 g', '11', '25', '32', '53', '60', 11)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (12, 'CHEESY BREAD ', '12 each', 'CHEESY BREAD ', '253 g', '65 g', '12', '26', '31', '54', '59', 12)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (13, 'AMERICAN SUB ', '13 each', 'AMERICAN SUB ', '263 g', '80 g', '13', '27', '30', '55', '58', 13)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (14, 'SPICY POTATO KALE ', '14 each', 'SPICY POTATO KALE ', '273 g', '81 g', '14', '28', '29', '56', '57', 14)
INSERT INTO [dbo].[RecipeNutritional] ([RecipeNutritionalID], [RecipeName], [RecipeItemServingDescription], [RecipeItemDescription], [RecipeItemCalories], [RecipeItemTotalFat], [RecipeItemCholesterol], [RecipeItemSodium], [RecipeItemPotassium], [RecipeItemTotalCarbohydrate], [RecipeItemProtein], [RecipeItemID]) VALUES (15, 'Rich''s Special', '15 Each', 'Description', '101 g', '1 g', '1', '2', '3', '4', '5', 6)
SET IDENTITY_INSERT [dbo].[RecipeNutritional] OFF
