ALTER TABLE [dbo].[EPSAccount]
    ADD CONSTRAINT [EPSAccount_PK] PRIMARY KEY CLUSTERED ([EPSAccountID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

