ALTER TABLE [dbo].[MenuGroup]
    ADD CONSTRAINT [PK_MenuGroup] PRIMARY KEY CLUSTERED ([MenuGroupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

