ALTER TABLE [dbo].[RecipeNutritional]
    ADD CONSTRAINT [PK_RecipeNutritional] PRIMARY KEY CLUSTERED ([RecipeNutritionalID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

