ALTER TABLE [dbo].[Recipe]
    ADD CONSTRAINT [PK_Recipe] PRIMARY KEY CLUSTERED ([RecipeItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

